version: '3'
services:
  strapi:
    container_name: strapi-container
    build: .
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_NAME: strapi
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    depends_on:
      - mysql
    networks:
      - strapi-net

  mysql:
    container_name: mysql-container
    image: mysql/mysql-server:8.0.13
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - strapi-net

networks:
  strapi-net:

volumes:
  db-data:
